version: "2.1"
services:
  ridesupport-profileconfig-ms:
    build: .
    ports:
      - "4002:4002"
    depends_on:
      ridesupport-profileconfig-db:
        condition: service_healthy
    healthcheck:
      test: "curl -I ridesupport-profileconfig-ms:4000/ridesupport-profileconfig-ms/resources/cars/ --fail"
      interval: 20s
      retries: 10
  ridesupport-profileconfig-db:
    image: mysql:5.7
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: car
      MYSQL_USER: sa
      MYSQL_PASSWORD: 2020i
    ports:
      - "3002:3306"
